### ISSUE TITLE
Pull requests/Todo list?

### ISSUE THREAD

**Issue by flumf** [aBradleyUno/RaspberryPi-XNU#1]
Great project :)
I really like the idea of it, and it honestly feels like darwin-on-arm is sorta coming back.
I was wondering if you had a todo list of things that should be implemented (such as filling in functions that were "stubbed" out) and perhaps building a toolchain to compile on *nix.

Also: you accepting pull reqs? :P

**Comment by adalric** [comment]
Thanks! Any help would be appreciated.

Right now there isn't a ToDo list per se, is more like, if it fails, fix it. The idea sounds nice, so I might add a ToDo.md. 

About the toolchain. DEFINITELY!! Jenkins on macOS isn't the best idea. 

And YES. If you have something to add feel free to tinker with the code!

**Comment by flumf** [comment]
Sounds good!
Just curious, you got a twitter or something that I can contact you on? Github issues isn't the *best* for trying to pass ideas back and forth ;P

**Comment by adalric** [comment]
You can find me @ABradleyUno on Twitter, although I almost never use it.

**Comment by flumf** [comment]
Sounds good!
`_not0x100` -> twitter
`xff@i2c-clk.org` -> email

I'm gonna start working on the toolchain rn

**Comment by matteyeux** [comment]
Are you planning to make some instructions ? It was a pain to build it as many things were missing

**Comment by flumf** [comment]
https://github.com/aBradleyUno/RaspberryPi-XNU/blob/02fd348faca2f19c12508e49432459b1eb6ac0ce/.travis.yml
The instructions there should work
(uses xcode 9.2)

**Comment by adalric** [comment]
I'm not good with words, but I gave it  a try at [Wiki - Building XNU](https://github.com/aBradleyUno/RaspberryPi-XNU/wiki/Building-XNU).

Hope it works! (based on that .travis.yml and [this blog](https://blog.fergofrog.com/xnu/arm64/2018/07/07/compile-xnu-for-arm64.html) )

**Comment by flumf** [comment]
Ok so for the toolchain, I think we can use the darwin-sdk.
I'm currently repacking it into a package that can be built with CMake (and latest gcc/clang)

**Comment by flumf** [comment]
So update(s):
I'm currently trying to get latest cctools to play nicely with everything else and it sucks. But hey, progress!
As for the todo list, here's some stuff that we need:
An open source bootloader to decompress a kernel and boot it
Some tool(s) to properly handle img4 files (unless we're just loading the kernel as a raw file)
