### ISSUE TITLE
Platform missing

### ISSUE THREAD

**Issue by adalric** [aBradleyUno/RaspberryPi-XNU#11]
I'm not completely sure but I think we need some kexts.

After

 ```
Reading startup extensions.
Loading Kernel External Components.
Reading built-in kernel personalities for I/O Kit drivers.
Sending all eligible registered kexts' personalities to the IOCatalogue but not starting matching.
0 kext personality sent to the IOCatalogue; matching not started.
```

Kernel panics with 

```
panic(cpu 0 caller 0xfffffff00785dd0c): "Unable to find driver for this platform: \"~~~~~~~~~~~~~~~~~~~~~~~~\".\n"
Nested panic detected:Kernel data abort. (saved state: 0xffffffe01b50aee0)
	  x0: 0xfffffff00700e852  x1:  0x0000000000000000  x2:  0x000000000000000d  x3:  0x0000000000000000
	  x4: 0x0000000000000001  x5:  0x0000000000000001  x6:  0x0000000000000000  x7:  0xffffffe01b4ebb64
	  x8: 0x0000000000000000  x9:  0xffffffe00020e080  x10: 0xffffffe00020e080  x11: 0x0000000000000000
	  x12: 0x0000000000000010 x13: 0x0000000000000066  x14: 0xffffffe002000000  x15: 0xfffffff007128e30
	  x16: 0xdeb8f177deb8f177 x17: 0xdeb8f177deb8f177  x18: 0xfffffff0072ed000  x19: 0xdeb8f177deb8f177
	  x20: 0x0000000000000000 x21: 0xffffffe01b50b4b0  x22: 0xfffffff0072ed534  x23: 0x00000000600003c4
	  x24: 0x0000000000000000 x25: 0x0000000000000000  x26: 0xdeb8f177deb8f177  x27: 0xdeb8f177deb8f177
	  x28: 0xdeb8f177deb8f177 fp:  0xffffffe01b50b250  lr:  0xfffffff007117db0  sp:  0xffffffe01b50b230
	  pc:  0xfffffff0072fbccc cpsr: 0x600003c4         esr: 0x96000005          far: 0x0000000000000014
```

The call trace is the following. 

<img width="323" alt="screen shot 2018-08-18 at 5 32 19 pm" src="https://user-images.githubusercontent.com/15053251/44303703-7e14e100-a30d-11e8-8190-57142fdac437.png">

Do you guys think this is the kernel asking us for the basic kexts or is it something else?

**Comment by zhuowei** [comment]
@aBradleyUno If you're wondering why the platform name is a bunch of tildes ("~~~~~"):

`modifydevicetree.py` probably erased the top level `compatible` node in the device tree.  In that script, I only [whitelisted](https://github.com/zhuowei/XNUQEMUScripts/blob/master/modifydevicetree.py#L5) the top level platform kext for the iPhone X, which has `compatible: b'D22AP\x00iPhone10,3\x00AppleARM\x00'`. 

This compatible property loads the AppleARMPlatform kext, so even if you fix the modifydevicetree to whitelist that property for your device tree, you'll still get this error since there's no kext - but at least you'll get a better platform name in the error.

**Comment by adalric** [comment]
@zhuowei Ok so I got the platform message in the panic, and while trying to build a kextcache I got this 
```

Unsupported.kext doesn't support architecture 'arm64'; skipping.
Private.kext doesn't support architecture 'arm64'; skipping.
Mach.kext doesn't support architecture 'arm64'; skipping.
MACFramework.kext doesn't support architecture 'arm64'; skipping.
Libkern.kext doesn't support architecture 'arm64'; skipping.
Kasan.kext doesn't support architecture 'arm64'; skipping.
IOKit.kext doesn't support architecture 'arm64'; skipping.
BSDKernel.kext doesn't support architecture 'arm64'; skipping.
Adding /Volumes/Darm64/System/Library/Extensions/System.kext/PlugIns/IOSystemManagement.kext to prelinked kernel.
Adding /Volumes/Darm64/System/Library/Extensions/System.kext/PlugIns/IONVRAMFamily.kext to prelinked kernel.
Adding /Volumes/Darm64/System/Library/Extensions/System.kext/PlugIns/ApplePlatformFamily.kext to prelinked kernel.
Adding /Volumes/Darm64/System/Library/Extensions/System.kext/PlugIns/AppleNMI.kext to prelinked kernel.
Adding /Volumes/Darm64/System/Library/Extensions/System.kext to prelinked kernel.

```
command `file /Volumes/Darm64/System/Library/Extensions/System.kext/PlugIns/Unsupported.kext/Unsupported` reveals something weird
```
/Volumes/Darm64/System/Library/Extensions/System.kext/PlugIns/Unsupported.kext/Unsupported: Mach-O 64-bit kext bundle ppc64

```

**Comment by zhuowei** [comment]
What command did you run to generate the kernelcache?

**Comment by adalric** [comment]
`sudo kextcache -z -a arm64 -c /Volumes/Darm64/kernelcache.debug -K BUILD/obj/mach.debug /Volumes/Darm64/System/Library/Extensions -v 6`

**Comment by adalric** [comment]
@zhuowei so, my bad, wrong cpu type there. Now `Assertion failed: (nNonSplitKexts), function __OSKextGetPLKSegSizes, file /BuildRoot/Library/Caches/com.apple.xbs/Sources/IOKitUser/IOKitUser-1483.201.1/kext.subproj/OSKext.c, line 16718.
zsh: abort      sudo kextcache -z -a arm64 -c /Volumes/Darm64/kernelcache.debug -K   -v 6`
