### ISSUE TITLE
RPI 4 compatibility

### ISSUE THREAD

**Issue by everdrone** [aBradleyUno/RaspberryPi-XNU#13]
I'm very interested in this project and I was wondering if this could run on the BCM2711, Raspberry Pi 4

**Comment by adalric** [comment]
It does! Sorta

You see, most of the components inside a RPi 4 don’t change that much from a RPi 3, the only things that do change are the addresses, so all you need is the proper EmbeddedDeviceTree pointing you to, let’s say, UART (for serial communication) and you are good to go. 

I’m still “working” on getting kexts to load with an U-Boot module tho, so when you do boot all you get is a panic after it fails to find any kext... 

Please take a look at [this](https://www.darm64.com/posts/building-xnu-for-pi/)

**Comment by everdrone** [comment]
Sounds great for now! Thanks!
Very curious about all the possibilities this could open, though this is not the right place to discuss them.

I will give it a try soon, very excited about this!
