### ISSUE TITLE
Help needed with Qemu

### ISSUE THREAD

**Issue by adalric** [aBradleyUno/RaspberryPi-XNU#3]
Currently we are able to build a mach0 binary, the boot process starts but panics everywhere... If you have experience with lldb please PM @abradleyuno on twitter.

**Comment by zhuowei** [comment]
@aBradleyUno For the MAX_CPUS assert: how many CPU nodes do you have in your device tree? https://github.com/Darm64/XNU/blob/master/pexpert/pexpert/arm64/board_config.h#L119 seems to suggest that there's a maximum of 3 CPUs expected in the device tree; the t8015 (iPhone X) device tree I was using with QEMU has 6 CPU nodes. Try grabbing a device tree from an iPhone 7.

**Comment by adalric** [comment]
I think I might remove that board configuration, it's not even being used.

**Comment by aBradleyUno** [comment]
Jenkins comment test
