### ISSUE TITLE
__DATA_CONST & __TEXT_EXEC missing in binary... Causing panics

### ISSUE THREAD

**Issue by adalric** [aBradleyUno/RaspberryPi-XNU#4]
https://github.com/Darm64/XNU/blob/1eb20fd85fa89f4f815d6b3e481171a8a9b34265/osfmk/arm64/arm_vm_init.c#L1224

**Comment by zhuowei** [comment]
@aBradleyUno do we need to add some extra sectcreate arguments in the arm64 ldflags? https://github.com/Darm64/XNU/blob/1eb20fd85fa89f4f815d6b3e481171a8a9b34265/makedefs/MakeInc.def#L364

**Comment by adalric** [comment]
Done, still, there is a panic every 15 LoC.

**Comment by zhuowei** [comment]
@aBradleyUno It seems that that isn't the right way to add a __DATA_CONST: https://github.com/apple-opensource/ld64/blob/master/src/ld/Options.cpp#L3808 says to pass in `-data_const` to the linker. Also, passing in `-text_exec` enables __TEXT_EXEC. https://github.com/apple-opensource/ld64/blob/master/src/ld/Options.cpp#L3816

My bad. :(

It looks like kexts are automatically compiled with these enabled (https://github.com/apple-opensource/ld64/blob/master/src/ld/Options.cpp#L4601), but there's no equivalent check for the kernel.

**Comment by adalric** [comment]
There is still the problem with the hardcoded offset. The assert still fails. https://github.com/Darm64/XNU/blob/1eb20fd85fa89f4f815d6b3e481171a8a9b34265/osfmk/arm64/arm_vm_init.c#L1338

**Comment by zhuowei** [comment]
@aBradleyUno we could try using `-segment_order` to reorder the segments manually

**Comment by adalric** [comment]
@zhuowei or -sectalign, I'm going to try both

**Comment by adalric** [comment]
-Wl,-segment_order,__TEXT:__DATA_CONST:__TEXT_EXEC:__KLD:__LAST:__DATA:__PRELINK_TEXT:__PLK_TEXT_EXEC:__PLK_DATA_CONST:__PRELINK_DATA:__PLK_LLVM_COV:__PLK_LINKEDIT:__PRELINK_INFO \

Am I missing something? @zhuowei

**Comment by zhuowei** [comment]
@aBradleyUno that looks fine.

**Comment by adalric** [comment]
@zhuowei still panics

**Comment by zhuowei** [comment]
@aBradleyUno What's the message now?

**Comment by adalric** [comment]
@zhuowei is still on the assert, the only difference are the value on the variables
Also check the segments, what does `__TEXT,initcode does? 
<img width="677" alt="screen shot 2018-08-17 at 12 23 54 pm" src="https://user-images.githubusercontent.com/15053251/44279797-6c054680-a218-11e8-96fa-042f05dfa048.png"> Left Darm64 - Right iOS 11.2.5

**Comment by zhuowei** [comment]
There's only two mentions of initcode in darwin-xnu: both are in kern_memorystatus.h

Edit: can I see the compiled kernel?

**Comment by adalric** [comment]
Maybe XNU_KERNEL_PRIVATE?

**Comment by adalric** [comment]
So, if I comment out the first assert the second one works like a charm

**Comment by adalric** [comment]
[XNU.zip](https://github.com/Darm64/XNU/files/2298343/Archive.zip)

**Comment by zhuowei** [comment]
@aBradleyUno The __TEXT section ends at 0xfffffff007204000, but the __DATA_CONST starts at 0xfffffff007400000 - this gap is causing the first assert to fire. It's interesting that __data_const aligned itself to the nearest 0x200000 byte; there's this in the makefile that seems relevant: https://github.com/Darm64/XNU/blob/c099cbfff60768d1dd735e74be0b3bb5ee9b1149/makedefs/MakeInc.def#L460

**Comment by adalric** [comment]
Well that solves it, that padding is the one messing the assert.
